import './globals.css';
import Footer from '@/components/footer';
import ClientProviders from './ClientProviders';
import Header from '../components/header';
import { Toaster } from 'react-hot-toast';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-sans">
      <body className="flex flex-col min-h-screen w-full">
        <ClientProviders>
          <Header /> {/* ✅ now inside <Provider> */}
          <main className="flex-grow w-full">{children}</main>
          <Footer />
          <Toaster position="top-right" reverseOrder={false} />
        </ClientProviders>
      </body>
    </html>
  );
}
