import './globals.css';
import Header from '../components/header';
import Footer from '@/components/footer';
import ClientProviders from './ClientProviders';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-sans">
      <body className="flex flex-col min-h-screen w-full">
        <Header />
        <ClientProviders>
          <main className="flex-grow w-full">{children}</main>
        </ClientProviders>
        <Footer />
      </body>
    </html>
  );
}
